language: r
sudo: false
cache: packages

before_install:
  - tlmgr install bera nowidow

r:
  - devel
bioc_required: true
bioc_use_devel: true

r: bioc-devel

warnings_are_errors: false

bioc_packages: BiocCheck

r_github_packages:
  - jimhester/covr
  
after_script:
  - R CMD BiocCheck *tar.gz  

after_success:
  - Rscript -e 'covr::codecov()'
